### ISSUE TITLE
Some papers

### ISSUE THREAD

**Issue by neubig** [simran-khanuja/awesome-cultural-nlp#1]
I took a look through some references that I had and the ACL anthology and found a few that might (or might not) be interesting to add!

- [x] [Cultural Concept Adaptation on Multimodal Reasoning](https://aclanthology.org/2023.emnlp-main.18.pdf)
- [x] [Knowledge of cultural moral norms in large language models](https://aclanthology.org/2023.acl-long.26.pdf)
- [x] [Cross-cultural variation of speech-accompanying gesture: A review](https://www.taylorfrancis.com/chapters/edit/10.4324/9781003059783-1/cross-cultural-variation-speech-accompanying-gesture-review-sotaro-kita)
- [x] [Probing Pre-Trained Language Models for Cross-Cultural Differences in Values](https://aclanthology.org/2023.c3nlp-1.12.pdf)
- [x] [Assessing Cross-Cultural Alignment between ChatGPT and Human Societies: An Empirical Study](https://aclanthology.org/2023.c3nlp-1.7.pdf)
- [x] [EnCBP: A New Benchmark Dataset for Finer-Grained Cultural Background Prediction in English](https://aclanthology.org/2022.findings-acl.221.pdf)
- [x] [Would you Rather? A New Benchmark for Learning Machine Alignment with Cultural Values and Social Preferences](https://aclanthology.org/2020.acl-main.477.pdf)
- [x] [SeeGULL: A Stereotype Benchmark with Broad Geo-Cultural Coverage Leveraging Generative Models](https://aclanthology.org/2023.acl-long.548.pdf)
- [x] [Cross-Cultural Analysis of Human Values, Morals, and Biases in Folk Tales](https://aclanthology.org/2023.emnlp-main.311.pdf)
- [x] [Cross-Cultural Similarity Features for Cross-Lingual Transfer Learning of Pragmatically Motivated Tasks](https://aclanthology.org/2021.eacl-main.204.pdf)
- [x] [Bridging Cultural Nuances in Dialogue Agents through Cultural Value Surveys](https://aclanthology.org/2024.findings-eacl.63.pdf)
- [x] [Social Commonsense for Explanation and Cultural Bias Discovery](https://aclanthology.org/2023.eacl-main.271.pdf)
- [x] [Global Voices, Local Biases: Socio-Cultural Prejudices across Languages](https://aclanthology.org/2023.emnlp-main.981.pdf)
- [x] [NORMSAGE: Multi-Lingual Multi-Cultural Norm Discovery from Conversations On-the-Fly](https://aclanthology.org/2023.emnlp-main.941.pdf)
- [x] [Multilingual Language Models are not Multicultural: A Case Study in Emotion](https://aclanthology.org/2023.wassa-1.19.pdf)

And the survey shouldn't forget these ones, which we certainly already know about :)

- [x] [Multi-lingual and Multi-cultural Figurative Language Understanding](https://aclanthology.org/2023.findings-acl.525.pdf)
- [x] [Visually Grounded Reasoning across Languages and Cultures](https://aclanthology.org/2021.emnlp-main.818.pdf)

**Comment by simran-khanuja** [comment]
done! #b0e1fa4

**Comment by neubig** [comment]
Fixed by https://github.com/simran-khanuja/awesome-cultural-nlp/commit/6a45b5bec45e27d414ddfad59dbcf419a693dd49
