### ISSUE TITLE
Missing dataset paper

### ISSUE THREAD

**Issue by shramay-palta** [simran-khanuja/awesome-cultural-nlp#2]
Just wanted to point to this dataset paper that appeared at ACL 2023 (Findings).

[FORK: A Bite-Sized Test Set for Probing Culinary Cultural Biases in Commonsense Reasoning Models](https://aclanthology.org/2023.findings-acl.631.pdf)

Here is the [dataset Github repo](https://github.com/shramay-palta/FORK_ACL2023)

**Comment by simran-khanuja** [comment]
thanks for sharing! please feel free to send a PR to add more resources I may have missed (which would be many, I'm sure :'))
